# Generated by Django 4.2.30 on 2026-06-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_path', models.CharField(max_length=512)),
                ('chat_group_id', models.CharField(db_index=True, max_length=128)),
                ('convention_path', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projects',
                'indexes': [models.Index(fields=['chat_group_id'], name='projects_chat_gr_4e983d_idx')],
            },
        ),
    ]
