# Generated by Django 4.2.30 on 2026-06-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
    ]
