# Generated by Django 4.2.30 on 2026-06-28 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('session_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('pid', models.CharField(blank=True, default='', max_length=32)),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('project_path', models.CharField(blank=True, default='', max_length=512)),
                ('command_line', models.CharField(blank=True, default='', max_length=512)),
                ('inputs', models.TextField(blank=True, default='')),
                ('logs', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Processing', max_length=32)),
                ('last_reported_log', models.TextField(blank=True, default='')),
                ('last_reported_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='task.task')),
            ],
            options={
                'db_table': 'agent_sessions',
                'indexes': [models.Index(fields=['status'], name='agent_sessi_status_51a545_idx')],
            },
        ),
    ]
