# Generated by Django 4.2.30 on 2026-06-28 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskIdempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('task_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task_idempotency',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('acceptance_criteria', models.TextField(blank=True, default='')),
                ('current_step', models.CharField(default='Requirement_Refinement', max_length=64)),
                ('current_status', models.CharField(default='Init', max_length=32)),
                ('affected_files', models.JSONField(default=dict)),
                ('sub_tasks', models.JSONField(default=list)),
                ('execution_logs', models.TextField(blank=True, default='')),
                ('code_diffs', models.JSONField(blank=True, default=list)),
                ('manual_edits', models.JSONField(blank=True, default=list)),
                ('fail_reason', models.TextField(blank=True, default='')),
                ('review_opinion', models.TextField(blank=True, default='')),
                ('checkpoint', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project')),
            ],
            options={
                'db_table': 'tasks',
                'indexes': [models.Index(fields=['project', 'current_step', 'current_status'], name='tasks_project_cae2bc_idx')],
            },
        ),
    ]
