# Generated by Django 4.2.30 on 2026-06-28 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookMessage',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('webhook_url', models.CharField(blank=True, default='', max_length=512)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='sent', max_length=32)),
                ('is_human', models.BooleanField(default=False)),
                ('sender_name', models.CharField(blank=True, default='', max_length=128)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
            options={
                'db_table': 'webhook_messages',
                'indexes': [models.Index(fields=['project', 'task'], name='webhook_mes_project_7c766b_idx')],
            },
        ),
    ]
